### ISSUE TITLE
Modify dependencies

### ISSUE THREAD

**Issue by chellimiller** [utori-dev/template-react-app-prototype#1]
We're wanting to update the dependencies:

 - [x] Remove `@mui/material`, it's overkill for many small apps.
 - [x] Add `@reduxjs/toolkit`, which is ideal for window state and theming.
 - [x] ~Add `redux-persist` for saving things not appropriate for `dexie` tables.~ #8 
 - [x] Add `clsx` for class names.
 - [x] Add `@floating-ui/react` for poppers, tooltips, dialogs, etc.
 - [x] Potentially add `usehooks-ts`
 - [x] Potentially add `type-fest`
 - [x] Update README with justifications/reasons for dependencies (not devDependencies)
 - [x] Move `dependencies` above `devDependencies`

**Comment by chellimiller** [comment]
@JaredBourget Did you try `redux-persist` with `@reduxjs/toolkit`?

It's from 4 years ago, so I'm wondering if we might be setting ourselves up for a hassle. I might create a separate ticket for `redux-persist` and potential alternatives specifically. We might be able to connect Redux to the Dexie database queries for settings/theming (and anything else).

**Comment by JaredBourget** [comment]
I have tried `redux-persist` with `redux-toolkit` and I didn't experience any issues when using it. It should be fairly simple to create some middleware to serialize and rehydrate to/from localStorage. At a fundamental level, I think that's all `redux-persist` is doing
