### ISSUE TITLE
Fix error when running tests on components connected to the state

### ISSUE THREAD

**Issue by chellimiller** [utori-dev/template-react-app-prototype#27]
Tests are failing for components connected to the state.

Below is an example:

![screenshot_jest-test-failure](https://github.com/utori-dev/template-react-app-prototype/assets/22763227/ea699ce6-d1b3-44f8-80d5-9c74cf708c90)

**Comment by JaredBourget** [comment]
Issue seemed to be related to `dexie`. The tests ran when I added 
```js
  moduleNameMapper: {
    '^dexie$': require.resolve('dexie'),
  },
```
to `jest.config.js`
