### ISSUE TITLE
Add additional scripts

### ISSUE THREAD

**Issue by JaredBourget** [utori-dev/template-react-app-prototype#3]
## Scripts to create

- [x] script to clean - something similar to `rm -rf dist/`

**Comment by chellimiller** [comment]
We used `rimraf` for this before, right?

**Comment by JaredBourget** [comment]
Yeah, I think we may have. 

I'll probably just add `"clean": "rimraf .cache .tmp lib dist build"` to the scripts then. On that note, do I have write access? I don't see an option to create a branch and I can't use the `--set-upstream origin` to create a branch

**Comment by chellimiller** [comment]
> Yeah, I think we may have.
> 
> I'll probably just add `"clean": "rimraf .cache .tmp lib dist build"` to the scripts then. On that note, do I have write access? I don't see an option to create a branch and I can't use the `--set-upstream origin` to create a branch

Oh dear! I'll check it the settings and make sure.

Edit: @JaredBourget I just added you as a maintainer to this specific repository, but I believe you have to accept the invitation. Next time we meet, let's make sure we have you set up to access everything for `utori-dev`
