### ISSUE TITLE
Update templates

### ISSUE THREAD

**Issue by chellimiller** [utori-dev/template-react-app-prototype#5]
The templates are a little frustrating.
 - They include a `className` component which is often unneeded as a prop in prototyping.
 - They are also declared as functions rather than as `const`, which makes assigning the type frustrating when dealing with special types of components.

For example, the `Component` template would probably be better if it was like this:

```tsx

/** Props for the FooBar */
export interface FooBarProps {
  // Your props here!
};


/**
 * Some description of FooBar
 *
 * @param props
 * @returns
 */
const FooBar: React.FC<FooBarProps> = (props) => {
  const { /* props */ } = props;

  return <div />;
};

export default FooBar;
```

Alternatively, we could try to incorporate styled components in the default template. Although it may make sense to have a different template for that.

**Comment by chellimiller** [comment]
@JaredBourget lmk what you think! I think this is a bit closer to our previous patterns.

**Comment by JaredBourget** [comment]
Yeah, your example is my preferred pattern for a component template.

Are you just thinking of including the import by default? Otherwise, I'm not sure how much sense it would make to incorporate styled components in the default template -  it seems like it would be heavily reliant on the meat of the component.

**Comment by chellimiller** [comment]
> Yeah, your example is my preferred pattern for a component template.
> 
> Are you just thinking of including the import by default? Otherwise, I'm not sure how much sense it would make to incorporate styled components in the default template - it seems like it would be heavily reliant on the meat of the component.

Agreed. I'll just keep it simple and use our preferred pattern.
