### ISSUE TITLE
Update app structure

### ISSUE THREAD

**Issue by chellimiller** [utori-dev/template-react-app-prototype#6]
We'll want an app structure that's a bit more user-friendly.

For starters, we'll probably want all Dexie database, Redux store, data types, and utilities under a single directory. Outside of the directory, we shouldn't need to know nor care if the data is from Redux, Dexie, or anywhere else.

Next, we'll want to include `icons/` and maybe a `styles/` directory. These could be under `src/` or `ui/`.
 - The `icons/` directory would be for custom SvgIcons and maybe have a base `SvgIcon` component.
 - The `styles/` directory would be for custom emotion styles.

Potentially, we could do something like this:

```
src/
    data/
      database/ <- Dexie for database
      store/ <- Redux for page-specific state and app settings
      types/ <- Types used within the app
      util/ <- Utilities for mapping and checking the data
    ui/
      ... components .../
      icons/
      styles/
    views/ <- Routes
```

We may want a generic, non-data `util/` directory, but that might be unneeded. We could just add that separately.

We'll also want to update templates to include generation for icons and potentially styles. Maybe this would be better for another ticket.

Todo:

- [x] Update app structure
- [x] Clean up Dexie database stuff and remove anything not being used.
- [x] Add Redux store
- [x] Add `SvgIcon`
- [x] Update ESLint configuration
- [x] #14
- [x] Update README

**Comment by chellimiller** [comment]
@JaredBourget What are your thoughts on the structure?

I recreated the [color-builder](https://github.com/chellimiller/color-builder/issues/1) app to see it in practice.

**Comment by JaredBourget** [comment]
Yeah, I agree that Dexie, the Redux store, and data types should be under the same directory. I'm not sure I like `data` as a directory name for it though, but I suppose if we're including the other elements, then something generic makes sense

If we want to add `icons/` and `styles/` to the `ui/` directory, I would prefer them to be under an `assets/`
```
.
└── ui/
    ├── assets/
    │   ├── images/
    │   └── styles/
    └── components/
```
But I don't plan on dying on any hills, not yet anyway

**Comment by chellimiller** [comment]
> Yeah, I agree that Dexie, the Redux store, and data types should be under the same directory. I'm not sure I like `data` as a directory name for it though, but I suppose if we're including the other elements, then something generic makes sense

Agreed. What do you think of `state/`? That's what I went with in the [color-builder test](https://github.com/chellimiller/color-builder).

> If we want to add `icons/` and `styles/` to the `ui/` directory, I would prefer them to be under an `assets/`
> 
> ```
> .
> └── ui/
>     ├── assets/
>     │   ├── images/
>     │   └── styles/
>     └── components/
> ```

`assets/` might give the impression of static assets like `foo.svg` images and `bar.css` styles, rather than React component icons and Emotion style sets. Although, now I'm realizing that the information above didn't make it clear which we were talking about. For static assets, I'm 100% onboard with that structure.

With that said, I think having `components/` is great. It will be way too messy without it.

What do you think of:

```
└── ui/
    ├── icons/ <- React component icons
    ├── emotion/
    └── components/
 ```

And reserve `assets/` for the future, in the event we want to include additional CSS or image files?
