### ISSUE TITLE
Review ESLint settings

### ISSUE THREAD

**Issue by chellimiller** [utori-dev/template-react-app-prototype#7]
Some of the settings may be too strict, especially for prototyping.

On a prototype made off of this template, I turned the following rules off:
 - `no-restricted-exports`
 - `react/prop-types`
 - `react/jsx-props-no-spreading`
 - `react/function-component-definition`
 
These should also probably be tossed:
 - `react/require-default-props`

**Comment by chellimiller** [comment]
@JaredBourget lmk what you think, I'm pretty sure we had these off at Olive.

**Comment by JaredBourget** [comment]
I think these can be turned off. 

`react/function-component-definition` forces you to use
```js
function HelloWorld() {
  return ...
}
```
instead of
```js
const HelloWorld = () => {
   return ...
}
```
yes?

**Comment by chellimiller** [comment]
> I think these can be turned off.
> 
> `react/function-component-definition` forces you to use
> 
> ```js
> function HelloWorld() {
>   return ...
> }
> ```
> 
> instead of
> 
> ```js
> const HelloWorld = () => {
>    return ...
> }
> ```
> 
> yes?

Yeah, it's from the Airbnb settings. However, we're both pretty used to the `const HelloWorld = ...` style so we can toss.
